BayDA parking location code changes
SANDAG/activitysim pull request #46
Opened 2022-09-27 17:40 UTC by kulshresthaa

2022-09-27 21:49 UTC, kulshresthaa commented
@dhensle This PR is ready for your review. Thanks!

2022-09-27 23:01 UTC, dhensle requested changes

2022-10-18 21:08 UTC, kulshresthaa commented on activitysim/abm/models/parking_location_choice.py
> +
Do you mean `network_los` isn't needed or `skims` needs to be added in locals_dict?

2022-10-18 21:08 UTC, kulshresthaa commented on activitysim/abm/models/parking_location_choice.py
> +        locals_dict = {}
got rid of the alts preprocssor, as it wasn't needed.

2022-11-03 18:25 UTC, dhensle commented on activitysim/abm/models/parking_location_choice.py
> +
I mean that the skims need to be in the locals_dict somehow, whether this is through the `network_los` object or the some other `skims` object doesn't really matter to me.  I suggested above just adding `network_los`.

2022-11-08 00:42 UTC, merged

2022-11-08 00:43 UTC, dhensle commented on activitysim/abm/models/parking_location_choice.py
> +
I just kept the network_los object in there upon merging.